mainApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

news/urls.py
from django.urls import path

from . import views
from django.views.generic import ListView, DetailView
from news.models import Articles, Category

app_name = 'news'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
]

news_feed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('news/', include('news.urls')),
    path('', include('mainApp.urls')),
    path('admin/', admin.site.urls),
]

registration/backends/activation/urls.py
"""
URLconf for registration and activation, using django-registration's
HMAC activation workflow.

"""

from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^activate/complete/$',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='django_registration_activation_complete'),
    # The activation key can make use of any character from the
    # URL-safe base64 alphabet, plus the colon as a separator.
    url(r'^activate/(?P<activation_key>[-:\w]+)/$',
        views.ActivationView.as_view(),
        name='django_registration_activate'),
    url(r'^register/$',
        views.RegistrationView.as_view(),
        name='django_registration_register'),
    url(r'^register/complete/$',
        TemplateView.as_view(
            template_name='django_registration/registration_complete.html'
        ),
        name='django_registration_complete'),
    url(r'^register/closed/$',
        TemplateView.as_view(
            template_name='django_registration/registration_closed.html'
        ),
        name='django_registration_disallowed'),
]

registration/backends/one_step/urls.py
"""
URLconf for registration using django-registration's one-step
workflow.

"""

from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views
from django.urls import path

urlpatterns = [
    path('register/',
        views.RegistrationView.as_view(),
        name='django_registration_register'),
    path('register/closed/',
        TemplateView.as_view(
            template_name='registration/registration_closed.html'
        ),
        name='django_registration_disallowed'),
    path('register/complete/',
        TemplateView.as_view(
            template_name='registration/registration_complete.html'
        ),
        name='django_registration_complete'),
]

mainApp/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(max_length=200)
    def __str__(self):
        return self.title

class Articles(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    pub_date = models.DateTimeField('date published')
    image = models.ImageField(upload_to='imagination', blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.title

mainApp/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse

from django.contrib.auth import authenticate, login

def index(request):
    return render(request, 'mainApp/homePage.html')

def contact(request):
    # username = request.POST['username']
    # password = request.POST['password']
    # user = authenticate(request, username=username, password=password)
	return render(request, 'mainApp/basic.html', {'values':['Если есть вопросы, то не звони', '0699']})

news/views.py
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic.detail import DetailView
from .models import Category, Articles
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render_to_response
import django_filters

# @login_required(login_url='/accounts/login/')

class IndexView(generic.ListView):
    template_name = 'news/posts.html'
    context_object_name = 'category_list'
    model = Category
    # paginate_by=1
    def get_queryset(self, *args, **kwargs):
        context = {}
        search_category = self.request.GET.get('q')
        if search_category is not None:
            list_category = Category.objects.filter(title__icontains=search_category)

            # формируем строку URL, которая будет содержать последний запрос
            # Это важно для корректной работы пагинации
            last_category = '?q=%s' % search_category

            current_page = Paginator(list_category, 10)

            page = self.request.GET.get('page')
            try:
                category_list = current_page.page(page)
            except PageNotAnInteger:
                category_list = current_page.page(1)
            except EmptyPage:
                category_list = current_page.page(current_page.num_pages)
        else:
            search_category = Category.objects.all()
            current_page = Paginator(search_category, 1)
            page = self.request.GET.get('page')
            try:
                category_list = current_page.page(page)
            except PageNotAnInteger:
                category_list = current_page.page(1)
            except EmptyPage:
                category_list = current_page.page(current_page.num_pages)
        return category_list

def detail(request, article_id):
    article = get_object_or_404(Articles, pk=article_id)
    return render(request, 'news/post.html', {'article': article})

mainApp/templates/mainApp/basic.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
	{% for val in values %}
		<h3>
			{{val}}
		</h3>
	{% endfor %}

<!-- Contact section start -->
<div id="contact" class="contact">
		<div class="container">
			<div class="span9 center contact-info">
				{% for val in values %}
				<p>{{val}}</p>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
<!-- Contact section edn -->
{% endblock %}

mainApp/templates/mainApp/homePage.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<h1 class="cover-heading">Это сайт с не очень интересными новостями.</h1>
{% if user.is_authenticated %}
    <h4>Привет, {{user}}.</h4>
{% else %}
    <h4>Если хочешь больше контента, то необходимо авторизоваться.</h4>
{% endif %}
<!--{% include "mainApp/includes/some_html.html" %}-->

{% endblock %}

mainApp/templates/mainApp/includes/some_html.html
{% block content %}
Это просто блок include

{% endblock %}

mainApp/templates/mainApp/wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Блог</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
    {% load staticfiles %}
<!--    <link rel="stylesheet" href="{% static 'mainApp/css/cover.css' %}" type="text/css">-->

    <!-- Load Roboto font -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <!-- Load css styles -->
<!--    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/bootstrap.css' %}" />-->
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/bootstrap-responsive.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/basic.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/pluton.css' %}" />
    <!--[if IE 7]>
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/pluton-ie7.css' %}" />
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/jquery.cslider.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/jquery.bxslider.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/animate.css' %}" />
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'mainApp/image/ico/apple-touch-icon-144.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'mainApp/image/ico/apple-touch-icon-114.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'mainApp/image/apple-touch-icon-72.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'mainApp/image/ico/apple-touch-icon-57.png' %}">
    <link rel="shortcut icon" href="{% static 'mainApp/image/ico/favicon.ico' %}">
</head>
<body>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">Fixed navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact">Contact</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="/news">News</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/">Sign out</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next=/news">Sign in</a></li>
    <!--                    <a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Sign up</a>-->
                    {% endif %}
                </ul>
                <!-- Search -->
                <form action="/news/" class="form-inline mt-2 mt-md-0" method="get">
                    <div class="input-group">
                        <input id="search" name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </nav>
    </header>
    <main role="main" class="flex-shrink-0">
    {% block content %}
    {% endblock %}
    </main>
    <!-- Footer section start -->
<footer class="footer mt-auto py-3">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>
    <!-- Footer section end -->
    <!-- ScrollUp button start -->
    <div class="scrollup">
        <a href="#">
            <i class="icon-up-open"></i>
        </a>
    </div>
    <!-- ScrollUp button end -->
    <!-- Include javascript -->
    <script src="{% static 'mainApp/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'mainApp/js/jquery.mixitup.js' %}"></script>
    <script type="text/javascript" src="{% static 'mainApp/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'mainApp/js/modernizr.custom.js' %}"></script>
    <script type="text/javascript" src="{% static 'mainApp/js/jquery.bxslider.js' %}"></script>
    <script type="text/javascript" src="{% static 'mainApp/js/jquery.cslider.js' %}"></script>
    <script type="text/javascript" src="{% static 'mainApp/js/jquery.placeholder.js' %}"></script>
    <script type="text/javascript" src="{% static 'mainApp/js/jquery.inview.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="{% static 'mainApp/js/respond.min.js' %}"></script>
    <![endif]-->
    <script type="text/javascript" src="{% static 'mainApp/js/app.js' %}"></script>
</body>
</html>

news/templates/news/post.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<div class="section secondary-section" id="portfolio">
	<div class="triangle"></div>
	<div class="container">
		<div id="single-project">
			<div id="slidingDiv" class="row-fluid single-project">
				<div class="span6">
					{% if article.image %}
						<img src="{{article.image}}" alt="{{article.title}}">
					{% else %}
						<img data-src="holder.js/200x250?theme=thumb" alt="{{article.title}}" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16a2ec66c6a%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16a2ec66c6a%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2256.203125%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E">
					{% endif %}
				</div>
				<div class="span6">
					<div class="project-description">
						<div class="project-title clearfix">
							<h3>{{article.title}}</h3>
						</div>
						<div class="project-info">
							<div>
								<span>Author</span>{{article.author}}
							</div>
							<div>
								<span>Date</span>{{article.pub_date|date:"d-m-Y в H:i:s"}}
							</div>
						</div>
						<p>{{article.text|safe|linebreaks}}</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

news/templates/news/posts.html
{% extends "mainApp/wrapper.html" %}


{% block content %}
<!-- Start home section -->
<div id="home">
    <!-- News-->
    {% if category_list %}
        {% for category in category_list %}
            <!-- Start cSlider -->
            <div id="da-slider" class="da-slider">
                <div class="triangle"></div>
                <!-- mask elemet use for masking background image -->
                <div class="mask"></div>
                <!-- All slides centred in container element -->
                <div class="container">
                    {% for article in category.articles_set.all %}
                    <!-- Start slide -->
                        <div class="da-slide">
                            <h2 class="fittext2">{{article.title}}</h2>
                            <h4>{{article.pub_date|date:"d-m-Y"}}</h4>
                            <p>{{article.text|safe|linebreaks}}</p>
                            <a href="/news/{{article.id}}" class="da-link button">Read more</a>
                            <div class="da-img">
                                {% if article.image %}
                                    <img src="{{article.image}}" alt="{{article.title}}" style="width: 320px; height: 250px;">
                                {% else %}
                                    <img data-src="holder.js/200x250?theme=thumb" alt="{{article.title}}" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16a2ec66c6a%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16a2ec66c6a%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2256.203125%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" style="width: 300px;">
                                {% endif %}
                            </div>
                        </div>
                    <!-- End slide -->
                    {% endfor %}
                    <!-- Start cSlide navigation arrows -->
                    <div class="da-arrows">
                        <span class="da-arrows-prev"></span>
                        <span class="da-arrows-next"></span>
                    </div>
                    <!-- End cSlide navigation arrows -->
                </div>
            </div>
            <!-- End cSlider -->
        {% endfor %}
    {% endif %}
    <div>
        {% if category_list %}
        <nav class="blog-pagination">
            {% if category_list.has_previous %}
            <a class="btn btn-outline-primary" href="/news?page={{ category_list.previous_page_number }}">Older</a>
            {% else %}
            <a class="btn btn-outline-primary disabled" href="">Older</a>
            {% endif %}
            {% for i in category_list.paginator.page_range %}
            {% if category_list.number == i %}
            <span class="active">{{ i }} <span class="sr-only">(current)</span></span>
            {% else %}
            <a href="?page={{ i }}">{{ i }}</a>
            {% endif %}
            {% endfor %}
            {% if category_list.has_next %}
            <a class="btn btn-outline-secondary" href="/news?page={{ category_list.next_page_number }}">Newer</a>
            {% else %}
            <a class="btn btn-outline-secondary disabled" href="">Newer</a>
            {% endif %}
        </nav>
        {% endif %}
    </div>
</div>
<!-- End home section -->
{% endblock %}

templates/django_registration/registration_closed.html
{% extends "mainApp/wrapper.html" %}

templates/django_registration/registration_complete.html
{% extends "mainApp/wrapper.html" %}
# шаблон окончания регистрации
{% block content %}
<h1>Регистрация завершена</h1>
Спасибо за уделённое время. На ваш e-mail отправлен
код подтверждения. Необходимо подтвердить регистрацию,
просто кликнув по указанной ссылке.<br/><br/>
{% endblock %}

templates/django_registration/registration_form.html
{% extends "mainApp/wrapper.html" %}
{% block content %}
<h1>Регистрация</h1>
<form method="post" action="">
    <dl class="register">
        {% for field in form %}
        <dt>{{ field.label_tag }}</dt>
        <dd class="clearfix">{{ field }}
            {% if field.help_text %}<div class="clearfix">{{ field.help_text }}</div>{% endif %}
            {% if field.errors %}<div class="myerrors clearfix">{{ field.errors }}</div>{% endif %}
        </dd>
        {% endfor %}
    </dl>
    <input type="submit" value="Зарегистрироваться" class="clearfix">
</form>
{% endblock %}